//ADD_ITEM_TO_CART
//REMOVE_ITEM_FROM_CART
//CART_ITEM_CLEAR

//CART_SAVE_SHIPPING_ADDRESS
//CART_SAVE_PAYMENT_METHOD


export const ADD_ITEM_TO_CART = "ADD_ITEM_TO_CART";
export const REMOVE_ITEM_FROM_CART = "REMOVE_ITEM_FROM_CART";
export const CART_ITEM_CLEAR = "CART_ITEM_CLEAR";

export const CART_SAVE_SHIPPING_ADDRESS = "CART_SAVE_SHIPPING_ADDRESS";
export const CART_SAVE_PAYMENT_METHOD = "CART_SAVE_PAYMENT_METHOD";
